<?php

use Illuminate\Database\Seeder;

class SysMinTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sys_min')->delete();
        
        \DB::table('sys_min')->insert(array (
            0 => 
            array (
                'id' => 1,
                'MI_MINCD' => '06',
                'MI_LANG' => '1',
                'MI_DESC' => 'LEMBAGA KEMAJUAN PERLANCONGAN MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => 'M',
                'MI_CREBY' => 'PGKU_HQ1',
                'MI_CREDT' => '2004-05-25 12:35:24',
                'MI_MODBY' => 'PGKU_HQ1',
                'MI_MODDT' => '2004-05-25 12:35:24',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Tingkat 17, 24-27 dan 30, Menara Dato\'Onn, Pusat Dagangan Dunia Putra,
45 Jalan Tun Ismail, Kuala Lumpur',
                'MI_POSCD' => '50710',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '269355188',
                'MI_FAXNO' => '26935884',
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'MI_MINCD' => '01',
                'MI_LANG' => '1',
                'MI_DESC' => 'KEMENTERIAN KESIHATAN   ',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => 'A',
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-02-13 17:31:09',
                'MI_MODBY' => '444444444444',
                'MI_MODDT' => '2012-05-15 17:14:54',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Tingkat 10, Bangunan PKNS, Jalan Raja Laut',
                'MI_POSCD' => '22333',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-23232345',
                'MI_FAXNO' => '03-34234332',
                'MI_EMAIL' => 'HEALTH@GOV.MY    ',
                'MI_OFFNM' => ' ',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'MI_MINCD' => '02',
                'MI_LANG' => '1',
                'MI_DESC' => 'KEM PERUMAHAN DAN KERAJAAN TEMPATAN',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => 'M',
                'MI_CREBY' => 'PGKU_HQ1',
                'MI_CREDT' => '2004-05-21 10:38:17',
                'MI_MODBY' => 'PGKU_HQ1',
                'MI_MODDT' => '2004-05-21 10:38:17',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'BHG. PENGAWASAN DAN PENGUATKUASA
ARAS 2, BLOK B(UTARA) PUSAT BANDAR DAMANSARA, PETI SURAT 12579, 
KUALA LUMPUR',
                'MI_POSCD' => '50782',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '20936714',
                'MI_FAXNO' => '20925409',
                'MI_EMAIL' => 'PRO@KPKT.GOV.MY',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'MI_MINCD' => '03',
                'MI_LANG' => '1',
                'MI_DESC' => 'KEMENTERIAN KERJA RAYA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => 'M',
                'MI_CREBY' => 'PGKU_HQ1',
                'MI_CREDT' => '2004-05-22 10:52:47',
                'MI_MODBY' => 'PGKU_HQ1',
                'MI_MODDT' => '2004-05-22 10:52:47',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Blok a, Komplek Kerja raya,
Jalan Sultan Salahuddin
Kuala Lumpue',
                'MI_POSCD' => '50580',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '27111100',
                'MI_FAXNO' => '27116612',
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'MI_MINCD' => '04',
                'MI_LANG' => '1',
                'MI_DESC' => 'BANK NEGARA MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => 'M',
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2008-08-19 09:35:33',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2008-08-19 09:35:33',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Unit Penyiasat Khas
Jalan Dato\' Onn
Kuala Lumpur',
                'MI_POSCD' => '50480',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-26988044',
                'MI_FAXNO' => '03-26912990',
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => 'EN. MAZLAN BIN AHMAD',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'MI_MINCD' => '05',
                'MI_LANG' => '1',
                'MI_DESC' => 'JABATAN ALAM SEKITAR',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => 'M',
                'MI_CREBY' => 'PGKU_HQ1',
                'MI_CREDT' => '2004-05-25 12:47:52',
                'MI_MODBY' => 'PGKU_HQ1',
                'MI_MODDT' => '2004-05-25 12:47:52',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Aras 6, Blok C5, Parcel C,
Pusat Pentadbiran Kerajaan Persekutuan
Putrajaya',
                'MI_POSCD' => '62662',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '88858200',
                'MI_FAXNO' => '88889987',
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'MI_MINCD' => '07',
                'MI_LANG' => '1',
                'MI_DESC' => 'JABATAN KEMAJUAN ISLAM MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => 'M',
                'MI_CREBY' => 'PGKU_HQ1',
                'MI_CREDT' => '2004-05-25 12:47:36',
                'MI_MODBY' => 'PGKU_HQ1',
                'MI_MODDT' => '2004-05-25 12:47:36',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Aras 4 & 9, Blok D7, Parcel D,
Pusat Pentadbiran kerajaan Persekutuan
Putrajaya',
                'MI_POSCD' => '62519',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '88864000',
                'MI_FAXNO' => '88892039',
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'MI_MINCD' => '10',
                'MI_LANG' => NULL,
                'MI_DESC' => 'JABATAN PENGANGKUTAN JALAN',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'PGKU_HQ1',
                'MI_CREDT' => '2004-05-25 12:47:10',
                'MI_MODBY' => 'PGKU_HQ1',
                'MI_MODDT' => '2004-05-25 12:47:10',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Aras 4, Blok D4, Parcel D,
Pusat Pentadbiran Kerajaan Persekutuan
Putrajaya',
                'MI_POSCD' => '62616',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '88866400',
                'MI_FAXNO' => '88889645',
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'MI_MINCD' => '08',
                'MI_LANG' => NULL,
                'MI_DESC' => 'SURUHANJAYA KOMUNIKASI DAN MULTIMEDIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'PGKU_HQ1',
                'MI_CREDT' => '2004-05-25 12:42:04',
                'MI_MODBY' => 'PGKU_HQ1',
                'MI_MODDT' => '2004-05-25 12:42:04',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Aras 11, Menara Dato Onn, 
Pusat Dagangan Dunia Putra
45, Jalan Tun Ismail, K. Lumpur',
                'MI_POSCD' => '50580',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '40477000',
                'MI_FAXNO' => '26940943',
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'MI_MINCD' => '09',
                'MI_LANG' => NULL,
                'MI_DESC' => 'POLIS DIRAJA MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'PGKU_HQ1',
                'MI_CREDT' => '2004-05-25 12:44:02',
                'MI_MODBY' => '830613106012',
                'MI_MODDT' => '2015-07-08 03:00:23',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Bukit Aman
Kuala Lumpur',
                'MI_POSCD' => '50560',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '22626222',
                'MI_FAXNO' => '26980503',
                'MI_EMAIL' => 'RMP@RMP.GOV.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'MI_MINCD' => '99',
                'MI_LANG' => NULL,
                'MI_DESC' => 'LAIN-LAIN AGENSI',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'LEE',
                'MI_CREDT' => '2004-01-05 09:02:16',
                'MI_MODBY' => '830613106012',
                'MI_MODDT' => '2015-05-18 03:52:58',
                'MI_STATECD' => '16',
                'MI_ADDR' => '',
                'MI_POSCD' => '',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '',
                'MI_FAXNO' => '',
                'MI_EMAIL' => '',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'MI_MINCD' => '11',
                'MI_LANG' => NULL,
            'MI_DESC' => 'KEMENTERIAN KESIHATAN MALAYSIA (BAHAGIAN FARMASI)',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'PGKU_HQ1',
                'MI_CREDT' => '2004-05-25 12:53:36',
                'MI_MODBY' => 'PGKU_HQ1',
                'MI_MODDT' => '2004-05-25 12:53:36',
                'MI_STATECD' => '10',
                'MI_ADDR' => 'Beg Berkunci No. 924,
Pejabat Pos Jalan Sultan,
Petaling Jaya',
                'MI_POSCD' => '46790',
                'MI_DISTCD' => '1008',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '79682200',
                'MI_FAXNO' => '79682222',
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'MI_MINCD' => '0702',
                'MI_LANG' => NULL,
                'MI_DESC' => 'JABATAN PENGANGKUTAN AWAM NEGERI JOHOR',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-11-05 08:49:00',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-11-05 08:49:00',
                'MI_STATECD' => '01',
                'MI_ADDR' => 'Kompleks JPJ,
Karung Berkunci No. 714',
                'MI_POSCD' => '80990',
                'MI_DISTCD' => '0102',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => 'PENGARAH',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'MI_MINCD' => 'A101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI IPOH',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 07:16:23',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 07:16:23',
                'MI_STATECD' => '08',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '0803',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'MI_MINCD' => 'B101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI SHAH ALAM',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 07:17:35',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 07:17:35',
                'MI_STATECD' => '10',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '1008',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'MI_MINCD' => 'C101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI KUANTAN',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 07:18:44',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 07:18:44',
                'MI_STATECD' => '06',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '0604',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'MI_MINCD' => 'D101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI KOTA BAHRU',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 07:21:32',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 07:21:32',
                'MI_STATECD' => '03',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '0302',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'MI_MINCD' => 'J101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI JOHOR BHARU',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM2',
                'MI_CREDT' => '2007-08-23 15:20:37',
                'MI_MODBY' => 'SYSADM2',
                'MI_MODDT' => '2007-08-23 15:20:37',
                'MI_STATECD' => '01',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '0102',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'MI_MINCD' => 'K101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI ALOR SETAR',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 12:14:18',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 12:14:18',
                'MI_STATECD' => '02',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '0201',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'MI_MINCD' => 'L101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI LABUAN',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 12:15:23',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 12:15:23',
                'MI_STATECD' => '15',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '1501',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'MI_MINCD' => 'M101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI MELAKA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 12:15:50',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 12:15:50',
                'MI_STATECD' => '04',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '0403',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'MI_MINCD' => 'N101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI SEREMBAN',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 12:16:16',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 12:16:16',
                'MI_STATECD' => '05',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '0505',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'MI_MINCD' => 'P101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI PENANG',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 12:16:53',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 12:16:53',
                'MI_STATECD' => '07',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '0705',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'MI_MINCD' => 'Q101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI KUCHING',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 12:17:29',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 12:17:29',
                'MI_STATECD' => '13',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '1301',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'MI_MINCD' => 'R101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI KANGAR',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 12:18:09',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 12:18:09',
                'MI_STATECD' => '09',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '0901',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'MI_MINCD' => 'S101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI KOTA KINABALU',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 12:18:47',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 12:18:47',
                'MI_STATECD' => '12',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '1201',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'MI_MINCD' => 'T101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI KUALA TERENGGANU',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 12:19:28',
                'MI_MODBY' => '444444444444',
                'MI_MODDT' => '2012-04-04 17:32:00',
                'MI_STATECD' => '11',
                'MI_ADDR' => '',
                'MI_POSCD' => '',
                'MI_DISTCD' => '1104',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '',
                'MI_FAXNO' => '',
                'MI_EMAIL' => '',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'MI_MINCD' => 'A201',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI MANJUNG',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 12:20:48',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 12:20:48',
                'MI_STATECD' => '08',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '0802',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'MI_MINCD' => 'A301',
                'MI_LANG' => NULL,
                'MI_DESC' => 'AGENSI TELUK INTAN',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-06-15 12:21:25',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-06-15 12:21:25',
                'MI_STATECD' => '08',
                'MI_ADDR' => NULL,
                'MI_POSCD' => NULL,
                'MI_DISTCD' => '0801',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'MI_MINCD' => '0701',
                'MI_LANG' => NULL,
                'MI_DESC' => 'JABATAN KESIHATAN NEGERI JOHOR',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-11-05 08:48:10',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-11-05 08:48:10',
                'MI_STATECD' => '01',
                'MI_ADDR' => 'Tingkat 3 & 4, Blok B
Wisma persekutuan
Jalan Air Molek',
                'MI_POSCD' => '80628',
                'MI_DISTCD' => '0102',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => 'PENGARAH KESIHATAN NEGERI JOHO',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'MI_MINCD' => '0703',
                'MI_LANG' => NULL,
                'MI_DESC' => 'MAJLIS PERBANDARAN JOHOR BAHRU TENGAH',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-11-05 08:50:04',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-11-05 08:50:04',
                'MI_STATECD' => '01',
                'MI_ADDR' => 'Skudai',
                'MI_POSCD' => '81300',
                'MI_DISTCD' => '0102',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => 'YANG DIPERTUA',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'MI_MINCD' => '0704',
                'MI_LANG' => NULL,
            'MI_DESC' => 'PEJABAT MAJLIS BANDARAYA JOHOR BAHRU(MBJB)',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-11-05 08:51:59',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-11-05 08:51:59',
                'MI_STATECD' => '01',
                'MI_ADDR' => 'Jalan Dato Onn,
Peti Surat 232',
                'MI_POSCD' => '80720',
                'MI_DISTCD' => '0102',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'MI_MINCD' => '0705',
                'MI_LANG' => NULL,
                'MI_DESC' => 'JABATAN KASTAM & EKSAIS DIRAJA MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-11-05 08:53:11',
                'MI_MODBY' => '830613106012',
                'MI_MODDT' => '2015-04-03 09:45:22',
                'MI_STATECD' => '01',
                'MI_ADDR' => 'Kompleks Kastam Tanjung Puteri
Karung Berkunci 780',
                'MI_POSCD' => '80990',
                'MI_DISTCD' => '0102',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '',
                'MI_FAXNO' => '',
                'MI_EMAIL' => 'ADUAN@CUSTOMS.GOV.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'MI_MINCD' => '0706',
                'MI_LANG' => NULL,
                'MI_DESC' => 'PEJABAT  MAJLIS PERBADANAN KULAI',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-11-05 08:54:54',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-11-05 08:54:54',
                'MI_STATECD' => '01',
                'MI_ADDR' => 'Jalan Pejabat Kerajaan 
Kulai',
                'MI_POSCD' => '81000',
                'MI_DISTCD' => '0102',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'MI_MINCD' => '0707',
                'MI_LANG' => NULL,
                'MI_DESC' => 'BANK  NEGERA MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2004-11-05 08:57:23',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2004-11-05 08:57:23',
                'MI_STATECD' => '01',
                'MI_ADDR' => 'Cawangan Johor Bahru
Jalan Bukit Timbalan',
                'MI_POSCD' => '80000',
                'MI_DISTCD' => '0102',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'MI_MINCD' => '12',
                'MI_LANG' => NULL,
                'MI_DESC' => 'SURUHANJAYA KOPERASI MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2008-07-28 12:07:38',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2008-07-28 12:07:38',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'TINGKAT 5-7, BLOK J, PUSAT BANDAR DAMANSARA,',
                'MI_POSCD' => '50603',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '0320935098',
                'MI_FAXNO' => '0320935026',
                'MI_EMAIL' => 'SKMIP@SKM.GOV.MY',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'MI_MINCD' => 'D102',
                'MI_LANG' => NULL,
                'MI_DESC' => 'PEGAWAI KESIHATAN DAERAH KOTA BHARU',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM2',
                'MI_CREDT' => '2008-08-15 10:10:13',
                'MI_MODBY' => 'SYSADM2',
                'MI_MODDT' => '2008-08-15 10:10:13',
                'MI_STATECD' => '03',
                'MI_ADDR' => 'Pejabat Kesihatan Daerah Kota Bharu,
Jalan Doktor,
Kelantan.',
                'MI_POSCD' => '15000',
                'MI_DISTCD' => '0302',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '097414800 / 09741480',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => 'PUAN FARAZILA BT. JAFFAR',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'MI_MINCD' => 'D103',
                'MI_LANG' => NULL,
                'MI_DESC' => 'PEGAWAI KESIHATAN DAERAH BACHOK',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM2',
                'MI_CREDT' => '2008-08-15 10:14:28',
                'MI_MODBY' => 'SYSADM2',
                'MI_MODDT' => '2008-08-15 10:14:28',
                'MI_STATECD' => '03',
                'MI_ADDR' => 'Pejabat Kesihatan Daerah Bachok,
Bachok,
Kelantan.
Tel. No: 09-7788333, 09-7782826',
                'MI_POSCD' => '16300',
                'MI_DISTCD' => '0302',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '09-7788333/7782826',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => 'ENCIK MAT GHAHIT BIN MOHAMED',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'MI_MINCD' => '13',
                'MI_LANG' => NULL,
                'MI_DESC' => 'KEMENTERIAN PENGAJIAN TINGGI',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2008-08-19 09:44:28',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2008-08-19 09:44:28',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Aras 4, Blok E 3, Kompleks E,
Pusat Pentadbiran Kerajaan Persekutuan',
                'MI_POSCD' => '62505',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-88835306',
                'MI_FAXNO' => '03-88893921',
                'MI_EMAIL' => 'WEBMASTERKPT@MOHE.GOV.MY',
                'MI_OFFNM' => 'PEGAWAI PERHUBUNGAN AWAM',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'MI_MINCD' => 'D104',
                'MI_LANG' => NULL,
                'MI_DESC' => 'JABATAN KESIHATAN NEGERI KELANTAN',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2008-08-19 09:54:53',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2008-08-19 09:54:53',
                'MI_STATECD' => '03',
                'MI_ADDR' => 'Aras 5, Wisma Persekutuan',
                'MI_POSCD' => '15200',
                'MI_DISTCD' => '0302',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '09-7413300',
                'MI_FAXNO' => '09-7413333',
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => 'PN. HUDA BINTI JOHARI',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'MI_MINCD' => 'D105',
                'MI_LANG' => NULL,
                'MI_DESC' => 'IBU PEJABAT POLIS KONTIJEN KELANTAN',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2008-08-19 10:01:09',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2008-08-19 10:01:09',
                'MI_STATECD' => '03',
                'MI_ADDR' => 'Jalan Bayam',
                'MI_POSCD' => '15000',
                'MI_DISTCD' => '0302',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '09-7455622',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'IPK_KEL@RMP.GOV.MY',
                'MI_OFFNM' => 'EN. REZLAN BIN ABU BAKAR',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'MI_MINCD' => 'D106',
                'MI_LANG' => NULL,
                'MI_DESC' => 'TELEKOM MALAYSIA BERHAD',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'SYSADM1',
                'MI_CREDT' => '2008-08-20 09:25:33',
                'MI_MODBY' => 'SYSADM1',
                'MI_MODDT' => '2008-08-20 09:25:33',
                'MI_STATECD' => '03',
                'MI_ADDR' => 'Jalan Doktor',
                'MI_POSCD' => '15000',
                'MI_DISTCD' => '0302',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => NULL,
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'MI_MINCD' => 'CFM',
                'MI_LANG' => NULL,
                'MI_DESC' => 'COMMUNICATIONS & MULTIMEDIA CONSUMER FORUM OF MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-06 11:15:20',
                'MI_MODBY' => NULL,
                'MI_MODDT' => NULL,
                'MI_STATECD' => '14',
                'MI_ADDR' => '6-02, 6th Floor, Straits Trading Building, 
No. 2 Lebuh Pasar Besar, 

',
                'MI_POSCD' => '50050',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '+603 2692 3800 ',
                'MI_FAXNO' => '',
                'MI_EMAIL' => 'ENQUIRIES@CFM.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'MI_MINCD' => 'BNML',
                'MI_LANG' => NULL,
            'MI_DESC' => 'LAMAN INFORMASI NASIHAT DAN KHIDMAT (BNMLINK)',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-06 16:42:32',
                'MI_MODBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_MODDT' => '2012-07-06 17:05:31',
                'MI_STATECD' => '14',
            'MI_ADDR' => 'Laman Informasi Nasihat dan Khidmat (LINK)
Ground Floor, D Block,
Jalan Dato\' Onn 
',
                'MI_POSCD' => '50480',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '',
                'MI_FAXNO' => '',
                'MI_EMAIL' => '',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'MI_MINCD' => 'BNMT',
                'MI_LANG' => NULL,
                'MI_DESC' => 'LAMAN INFORMASI NASIHAT DAN KHIDMAT ',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-06 16:44:27',
                'MI_MODBY' => NULL,
                'MI_MODDT' => NULL,
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Bank Negara Malaysia
P.O. Box 10922

',
                'MI_POSCD' => '50929',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '1-300-88-5465',
                'MI_FAXNO' => '603-2174-1515',
                'MI_EMAIL' => 'BNMTELELINK@BNM.GOV.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'MI_MINCD' => 'SSM',
                'MI_LANG' => NULL,
                'MI_DESC' => 'SURUHANJAYA SYARIKAT MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-06 16:46:12',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 17:49:02',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Tingkat 28, Menara SSM@Sentrall
No. 7, Jalan Stesen Sentral 5, Kuala Lumpur Sentral',
                'MI_POSCD' => '50623',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '603 â€“ 2299 5500',
                'MI_FAXNO' => '603 - 2299 5461',
                'MI_EMAIL' => 'ADUAN@SSM.COM.MY',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '0',
            ),
            46 => 
            array (
                'id' => 47,
                'MI_MINCD' => 'BNKR',
                'MI_LANG' => NULL,
                'MI_DESC' => 'BANK RAKYAT',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-06 16:48:19',
                'MI_MODBY' => NULL,
                'MI_MODDT' => NULL,
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Unit Biro Aduan Awam
Norliza Mat Isa
Jabatan Komunikasi Korporat, 
Tingkat 11, Bangunan Bank Rakyat, 
Jalan Tangsi, Peti Surat 11024, 
50732 Kuala Lumpur
',
                'MI_POSCD' => '50732',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-26975011, 2697601',
                'MI_FAXNO' => '03-26129655',
                'MI_EMAIL' => 'ADUAN@BANKRAKYAT.COM.MY',
                'MI_OFFNM' => 'NORLIZA MAT ISA',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'MI_MINCD' => 'CYBE',
                'MI_LANG' => NULL,
                'MI_DESC' => 'CYBERSECURITY MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-17 13:40:08',
                'MI_MODBY' => NULL,
                'MI_MODDT' => NULL,
                'MI_STATECD' => '10',
                'MI_ADDR' => 'Level 8, Block A,
Mines Waterfront Business Park,
No 3 Jalan Tasik, The Mines Resort City,
Seri Kembangan,
',
                'MI_POSCD' => '43300',
                'MI_DISTCD' => '1004',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '+603 - 8946 0999',
                'MI_FAXNO' => '+603 - 8946 0888',
                'MI_EMAIL' => 'INFO@CYBERSECURITY.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'MI_MINCD' => 'SPAD',
                'MI_LANG' => NULL,
                'MI_DESC' => 'SURUHANJAYA PENGANGKUTAN AWAM DARAT ',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-17 13:41:24',
                'MI_MODBY' => NULL,
                'MI_MODDT' => NULL,
                'MI_STATECD' => '10',
                'MI_ADDR' => '',
                'MI_POSCD' => '',
                'MI_DISTCD' => '1001',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-88805540',
                'MI_FAXNO' => '',
                'MI_EMAIL' => 'ADUAN@SPAD.GOV.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'MI_MINCD' => 'TTPR',
                'MI_LANG' => NULL,
                'MI_DESC' => 'TRIBUNAL TUNTUTAN PEMBELI RUMAH',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-17 13:42:17',
                'MI_MODBY' => NULL,
                'MI_MODDT' => NULL,
                'MI_STATECD' => '10',
                'MI_ADDR' => '',
                'MI_POSCD' => '',
                'MI_DISTCD' => '1001',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-20998343',
                'MI_FAXNO' => '',
                'MI_EMAIL' => 'TRIBUNAL@KPKT.GOV.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'MI_MINCD' => 'TNB',
                'MI_LANG' => NULL,
                'MI_DESC' => 'TENAGA NASIONAL BERHAD ',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-17 13:43:03',
                'MI_MODBY' => NULL,
                'MI_MODDT' => NULL,
                'MI_STATECD' => '14',
                'MI_ADDR' => '',
                'MI_POSCD' => '',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-22825566',
                'MI_FAXNO' => '',
                'MI_EMAIL' => 'SMP@TNB.COM.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'MI_MINCD' => 'SBAS',
                'MI_LANG' => NULL,
                'MI_DESC' => 'SYARIKAT BEKALAN AIR SELANGOR ',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-17 13:43:43',
                'MI_MODBY' => NULL,
                'MI_MODDT' => NULL,
                'MI_STATECD' => '10',
                'MI_ADDR' => '',
                'MI_POSCD' => '',
                'MI_DISTCD' => '1008',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-22955160',
                'MI_FAXNO' => '',
                'MI_EMAIL' => 'PUSPEL@SYABAS.COM.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'MI_MINCD' => 'SJT',
                'MI_LANG' => NULL,
                'MI_DESC' => 'SURUHANJAYA TENAGA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-17 13:44:36',
                'MI_MODBY' => NULL,
                'MI_MODDT' => NULL,
                'MI_STATECD' => '16',
                'MI_ADDR' => '',
                'MI_POSCD' => '',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-88708500',
                'MI_FAXNO' => '',
                'MI_EMAIL' => 'AZLAN@ST.GOV.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'MI_MINCD' => 'PDRM',
                'MI_LANG' => NULL,
                'MI_DESC' => 'JABATAN SIASATAN JENAYAH KOMERSIL, POLIS DIRAJA MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-17 13:45:30',
                'MI_MODBY' => NULL,
                'MI_MODDT' => NULL,
                'MI_STATECD' => '14',
                'MI_ADDR' => '',
                'MI_POSCD' => '',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-26163822',
                'MI_FAXNO' => '',
                'MI_EMAIL' => 'URUSETIA_JSJK@RMP.GOV.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'MI_MINCD' => 'KKM',
                'MI_LANG' => NULL,
                'MI_DESC' => 'KEMENTERIAN KESIHATAN MALAYSIA',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => 'Ruzzaida Bt Kamaruldzaman',
                'MI_CREDT' => '2012-07-17 13:47:10',
                'MI_MODBY' => NULL,
                'MI_MODDT' => NULL,
                'MI_STATECD' => '14',
                'MI_ADDR' => '',
                'MI_POSCD' => '',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-88833470',
                'MI_FAXNO' => '',
                'MI_EMAIL' => 'PRO.KKM@MOH.GOV.MY',
                'MI_OFFNM' => '',
                'MI_OFFNM2' => NULL,
                'MI_STS' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'MI_MINCD' => '100',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Jabatan Perdana Menteri',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 17:50:27',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 17:50:27',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Seksyen Pengurusan Teknologi Maklumat, Bahagian Khidmat Pengurusan, Aras 1, Blok B8, Kompleks Jabatan Perdana Menteri, 62502, Putrajaya.',
                'MI_POSCD' => '62502',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'webadmin@jpm.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            56 => 
            array (
                'id' => 57,
                'MI_MINCD' => '101',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Kewangan Malaysia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 17:54:19',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 17:54:19',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Kementerian Kewangan Malaysia, No. 5, Persiaran Perdana, Presint 2, Pusat Pentadbiran Kerajaan Persekututan, 62592, WP Putrajaya',
                'MI_POSCD' => '62592',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'pro@treasury.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            57 => 
            array (
                'id' => 58,
                'MI_MINCD' => '102',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Pendidikan Malaysia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 18:49:37',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 18:49:37',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Kementerian Pendidikan Malaysia, Blok E8, Kompleks E, Pusat Pentadbiran Kerajaan Persekutuan, 62604, Putrajaya.',
                'MI_POSCD' => '62604',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'kpkkpm@moe.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            58 => 
            array (
                'id' => 59,
                'MI_MINCD' => '103',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Pertahanan',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 18:50:54',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 18:50:54',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Kementerian Pertahanan, Jalan Padang Tembak, 50634, Kuala Lumpur.',
                'MI_POSCD' => '50634',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => NULL,
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'portal@mod.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            59 => 
            array (
                'id' => 60,
                'MI_MINCD' => '104',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Pengangkutan Malaysia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 18:53:15',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 18:53:15',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Kementerian Pengangkutan Malaysia, No. 26, Jalan Tun Hussein, Presint 4, 62100, WP Putrajaya',
                'MI_POSCD' => '62100',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'aduan@mot.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            60 => 
            array (
                'id' => 61,
                'MI_MINCD' => '105',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Dalam Negeri Malaysia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 18:54:19',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 18:54:19',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Kementerian Dalam Negeri Malaysia, Blok D1, D2, & D9, Kompleks D, Pusat Pentadbiran Kerajaan Persekutuan, 62546, WP Putrajaya',
                'MI_POSCD' => '62546',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'webmaster@moha.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            61 => 
            array (
                'id' => 62,
                'MI_MINCD' => '106',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Kerja Raya Malaysia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 18:55:10',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 18:55:10',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Kementerian Kerja Raya Malaysia, Tingkat 1-4, Komples Kerja  Raya, Jalan Sultan Salahuddin, 50580, Kuala Lumpur',
                'MI_POSCD' => '50580',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'pro@kkr.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            62 => 
            array (
                'id' => 63,
                'MI_MINCD' => '107',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Perdagangan Antarabangsa dan Industri',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 18:56:11',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 18:56:11',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Kementerian Perdagangan Antarabangsa dan Industri, Menara MITI, No. 7, Jalan Sultan Haji Ahmad Shah, 50480, Kuala Lumpur, Malaysia.',
                'MI_POSCD' => '50480',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'webmiti@miti.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            63 => 
            array (
                'id' => 64,
                'MI_MINCD' => '108',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Luar Negeri',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 18:57:03',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 18:57:03',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Kementerian Luar Negeri, Wisma Putra, No. 1, Jalan Wisma Putra, Presint 2, 62602, Putrajaya',
                'MI_POSCD' => '62602',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'webmaster@kln.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            64 => 
            array (
                'id' => 65,
                'MI_MINCD' => '109',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Komunikasi dan Multimedia Malaysia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 18:57:57',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 18:57:57',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Kementerian Komunikasi dan Multimedia, Lot 4G9, Persiaran Perdana, Presint 4, Pusat Pentadbiran Kerajaan Persekutuan, 62100, WP Putrajaya.',
                'MI_POSCD' => '62100',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'webmaster@kkmm.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            65 => 
            array (
                'id' => 66,
                'MI_MINCD' => '110',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Suruhanjaya Komunikasi dan Multimedia Malaysia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:00:48',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:00:48',
                'MI_STATECD' => '10',
                'MI_ADDR' => 'MCMC Tower 1, Jalan Impact, Cyber 6, 63000 Cyberjaya, Selangor',
                'MI_POSCD' => '63000',
                'MI_DISTCD' => '1010',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8688 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'aduanskmm@cmcm.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            66 => 
            array (
                'id' => 67,
                'MI_MINCD' => '111',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Forum Pengguna Komunikasi dan Multimedia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:02:07',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:02:07',
                'MI_STATECD' => '14',
                'MI_ADDR' => '-',
                'MI_POSCD' => '00000',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-7805 1800',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'aduan@cfm.org.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            67 => 
            array (
                'id' => 68,
                'MI_MINCD' => '112',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Sumber Manusia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:03:08',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:03:08',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Blok D3 & D4, Kompleks D, 62502, Putrajaya',
                'MI_POSCD' => '62502',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'akpukk@mohr.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            68 => 
            array (
                'id' => 69,
                'MI_MINCD' => '113',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Kemajuan Luar Bandar & Wilayah',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:04:14',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:04:14',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'No. 47, Persiaran Perdana, Presint 4, Pusat Pentadbiran Kerajaan Persekutuan, 62100, Putrajaya',
                'MI_POSCD' => '62100',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'aduan@ruralink.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            69 => 
            array (
                'id' => 70,
                'MI_MINCD' => '114',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Kesejahteraan Bandar, Perumahan dan Kerajaan Tempatan',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:05:39',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:05:39',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'No. 51, Persiaran Perdana, Presint 4, 62100, Putrajaya',
                'MI_POSCD' => '62100',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'pro@kpkt.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            70 => 
            array (
                'id' => 71,
                'MI_MINCD' => '115',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Belia dan Sukan',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:06:38',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:06:38',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Menara KBS, No. 27, Persiaran Perdana, Presint 4, Pusat Pentadbiran Kerajaan Persekutuan, 62570, Putrajaya',
                'MI_POSCD' => '62570',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8871 3333/3000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'webmaster@kbs.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            71 => 
            array (
                'id' => 72,
                'MI_MINCD' => '116',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Kesihatan Malaysia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:07:42',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:07:42',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Blok E1, E3, E6, E7 & E10, Kompleks E, Pusat Pentadbiran Kerajaan Persekutuan, 62590, Putrajaya',
                'MI_POSCD' => '62590',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'kkm@moh.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            72 => 
            array (
                'id' => 73,
                'MI_MINCD' => '117',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Wilayah Persekutuan',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:28:04',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:28:04',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Blok 1 & Blok 2, Menara Seri Wilayah, Presint 2, 62100, Putrajaya',
                'MI_POSCD' => '62100',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'webmaster@kwp.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            73 => 
            array (
                'id' => 74,
                'MI_MINCD' => '118',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Perusahaan Perladangan & Komoditi',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:29:28',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:29:28',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'No 15, Aras 6-13, Persiaran Perdana, Presint 2, 62654, Putrajaya',
                'MI_POSCD' => '62654',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'webmaster@mpic.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            74 => 
            array (
                'id' => 75,
                'MI_MINCD' => '119',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Tenaga, Teknologi Hijau dan Air',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:30:20',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:30:20',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Blok E4/5, Kompleks Kerajaan Parcel E, Pusat Pentabiran Kerajaan Persekutuan, 62668, Putrajaya',
                'MI_POSCD' => '62668',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'webmaster@kettha.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            75 => 
            array (
                'id' => 76,
                'MI_MINCD' => '120',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Pertanian & Industri Asas Tani',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:31:31',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:31:31',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Blok 4G1, Wisma Tani, No. 28, Persiaran Perdana, Presint 4, Pusat Pentadbiran Kerajaan Persekutuan, 62624, Putrajaya',
                'MI_POSCD' => '62624',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8870 1200 / 1400',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'pro@moa.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            76 => 
            array (
                'id' => 77,
                'MI_MINCD' => '121',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Pelancongan dan Kebudayaan',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:32:16',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:32:16',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'No. 2, Menara 1, Jalan P5/6, Presint 5, 62200, Putrajaya',
                'MI_POSCD' => '62200',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'info@motac.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            77 => 
            array (
                'id' => 78,
                'MI_MINCD' => '122',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Sains, Teknologi dan Inovasi',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:33:21',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:33:21',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Aras 1-7, Blok C4 & C5, Kompleks C, Pusat Pentadbiran Kerajaan Persekutuan, 62662, Putrajaya',
                'MI_POSCD' => '62662',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'info@mosti.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            78 => 
            array (
                'id' => 79,
                'MI_MINCD' => '123',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Sumber Asli dan Alam Sekitar',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:34:08',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:34:08',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'Wisma Sumber Asli, No. 25, Persiaran Perdana, Presint 4, 62574, Putrajaya',
                'MI_POSCD' => '62574',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'aduannre@nre.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            79 => 
            array (
                'id' => 80,
                'MI_MINCD' => '124',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Kementerian Pembangunan Wanita, Keluarga dan Masyarakat',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:34:55',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:34:55',
                'MI_STATECD' => '16',
                'MI_ADDR' => 'No 55, Persiaran Perdana, Presint 4, 62100, Putrajaya',
                'MI_POSCD' => '62100',
                'MI_DISTCD' => '1601',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8000 8000',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'info@kpwkm.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            80 => 
            array (
                'id' => 81,
                'MI_MINCD' => '125',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Suruhanjaya Pengangkutan Awam Darat',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:35:55',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:35:55',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Blok D, Platinum Sentral, Jalan Stesen Sentral 2, Kuala Lumpur Sentral, 50470, Kuala Lumpur',
                'MI_POSCD' => '50470',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '1-800-88-7723',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'aduan@spad.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            81 => 
            array (
                'id' => 82,
                'MI_MINCD' => '126',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Suruhanjaya Perkhidmatan Air Negara',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:36:49',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:36:49',
                'MI_STATECD' => '10',
                'MI_ADDR' => 'Aras Bawah dan Aras Satu, Prima Avanue 7, Blok 3510, Jalan Teknokrat 6, 63000, Cyberjaya, Selangor',
                'MI_POSCD' => '63000',
                'MI_DISTCD' => '1010',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-8317 9333',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'span@span.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            82 => 
            array (
                'id' => 83,
                'MI_MINCD' => '127',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Bank Negara Malaysia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:38:08',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:38:08',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Jalan Dato\' Onn, 50480, Kuala Lumpur',
                'MI_POSCD' => '50480',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '1300 88 5465',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'bnmtelelink@bnm.gov.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            83 => 
            array (
                'id' => 84,
                'MI_MINCD' => '128',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Telekom Malaysia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:38:59',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:38:59',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Level 51. North Wing, Menara TM, Jalan Pantai Baru, 50672, Kuala Lumpur',
                'MI_POSCD' => '50672',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '1 300 888 123',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'help@tm.com.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            84 => 
            array (
                'id' => 85,
                'MI_MINCD' => '129',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Suruhanjaya Penerbangan Malaysia',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:39:45',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:39:45',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Tingkat 19, Menara 1 Sentrum, 201, Jalan Tun Sambanthan, 50470, Kuala Lumpur',
                'MI_POSCD' => '50470',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-2772 0677 / 0600',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'enquiries@mavcom.com.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            85 => 
            array (
                'id' => 86,
                'MI_MINCD' => '130',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Tenaga Nasional Berhad',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:40:42',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:40:42',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'No 129, Jalan Bangsar, 59200, Kuala Lumpur',
                'MI_POSCD' => '59200',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '03-2296 5566',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'tnbcareline@tnb.com.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
            86 => 
            array (
                'id' => 87,
                'MI_MINCD' => '131',
                'MI_LANG' => NULL,
                'MI_DESC' => 'Syarikat Bekalan Air Selangor',
                'MI_RVWBY' => NULL,
                'MI_INVBY' => NULL,
                'MI_MINTYP' => NULL,
                'MI_CREBY' => '1',
                'MI_CREDT' => '2017-11-20 19:41:26',
                'MI_MODBY' => '1',
                'MI_MODDT' => '2017-11-20 19:41:26',
                'MI_STATECD' => '14',
                'MI_ADDR' => 'Jalan Pantai Baharu, 59990, Kuala Lumpur',
                'MI_POSCD' => '59990',
                'MI_DISTCD' => '1401',
                'MI_COUNTRY' => NULL,
                'MI_TELNO' => '15300',
                'MI_FAXNO' => NULL,
                'MI_EMAIL' => 'puspel@syabas.com.my',
                'MI_OFFNM' => NULL,
                'MI_OFFNM2' => NULL,
                'MI_STS' => '1',
            ),
        ));
        
        
    }
}