<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateEnquiryPaperCaseTempsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('enquiry_paper_case_temps', function (Blueprint $table) {
            $table->increments('id');
            $table->text('a_negeri')->nullable();
            $table->text('b_cawangan')->nullable();
            $table->text('c_nokes')->nullable();
            $table->text('d_akta')->nullable();
            $table->text('e_tahun')->nullable();
            $table->text('f_bulan')->nullable();
            $table->text('g_asastindakan')->nullable();
            $table->text('h_tarikhkejadian')->nullable();
            $table->text('i_tarikhserahan')->nullable();
            $table->text('j_pengelasankes')->nullable();
            $table->text('k_kategorikesalahan')->nullable();
            $table->text('l_kesalahan')->nullable();
            $table->text('m_pegawaiserbuanro')->nullable();
            $table->text('n_pegawaipenyiasataio')->nullable();
            $table->text('o_pegawaipenyiasatio')->nullable();
            $table->text('p_noreportpolis')->nullable();
            $table->text('q_nossm')->nullable();
            $table->text('r_namapremissyarikat')->nullable();
            $table->text('s_alamat')->nullable();
            $table->text('t_jenama')->nullable();
            $table->text('u_kawasan')->nullable();
            $table->text('v_jenisperniagaan')->nullable();
            $table->text('w_kategoripremis')->nullable();
            $table->text('x_jenispremis')->nullable();
            $table->text('y_statusokt')->nullable();
            $table->text('z_jantina')->nullable();
            $table->text('aa_namaokt')->nullable();
            $table->text('ab_tarafkerakyatan')->nullable();
            $table->text('ac_noicpasport')->nullable();
            $table->text('ad_kategoribarangrampasan')->nullable();
            $table->text('ae_jenisbarangrampasan')->nullable();
            $table->text('af_jenisbarangrampasan2')->nullable();
            $table->text('ag_karyatempatanantarabangsa')->nullable();
            $table->text('ah_jenama')->nullable();
            $table->text('ai_bob')->nullable();
            $table->text('aj_nosealssm')->nullable();
            $table->text('ak_unit')->nullable();
            $table->text('al_tong')->nullable();
            $table->text('am_tangki')->nullable();
            $table->text('an_liter')->nullable();
            $table->text('ao_kg')->nullable();
            $table->text('ap_nilaiawardappsahaja')->nullable();
            $table->text('aq_nilairampasanrm')->nullable();
            $table->text('ar_nilaikenderaanrm')->nullable();
            $table->text('as_tarikhkompaundikeluarkan')->nullable();
            $table->text('at_bulankompaundikeluarkan')->nullable();
            $table->text('au_tahunkompaundikeluarkan')->nullable();
            $table->text('av_nilaikompaunditawarkan')->nullable();
            $table->text('aw_tarikhkompaundiserahkan')->nullable();
            $table->text('ax_bulankompaundiserahkan')->nullable();
            $table->text('ay_tahunkompaundiserahkan')->nullable();
            $table->text('az_tarikhkompaundibayar')->nullable();
            $table->text('ba_bulankompaundibayarh')->nullable();
            $table->text('bb_tahunkompaundibayar')->nullable();
            $table->text('bc_nilaikompaundibayar')->nullable();
            $table->text('bd_noresitpembayarankompaun')->nullable();
            $table->text('be_pegawaipendakwa')->nullable();
            $table->text('bf_mahkamah')->nullable();
            $table->text('bg_nopendaftaranmahkamah')->nullable();
            $table->text('bh_tarikhdaftarmahkamah')->nullable();
            $table->text('bi_bulandaftarmahkamah')->nullable();
            $table->text('bj_tahundaftarmahkamah')->nullable();
            $table->text('bk_tarikhsebutan')->nullable();
            $table->text('bl_tarikhsebutan')->nullable();
            $table->text('bm_tahunsebutan')->nullable();
            $table->text('bn_tarikhbicara')->nullable();
            $table->text('bo_bulanbicara')->nullable();
            $table->text('bp_tahunbicara')->nullable();
            $table->text('bq_tarikhdenda')->nullable();
            $table->text('br_bulandenda')->nullable();
            $table->text('bs_tahundenda')->nullable();
            $table->text('bt_nilaidendarm')->nullable();
            $table->text('bu_tarikhpenjara')->nullable();
            $table->text('bv_bulanpenjara')->nullable();
            $table->text('bw_tahunpenjara')->nullable();
            $table->text('bx_tempohpenjara')->nullable();
            $table->text('by_tarikhdnaa')->nullable();
            $table->text('bz_bulandnaa')->nullable();
            $table->text('ca_tahundnaa')->nullable();
            $table->text('cb_tarikhnfa')->nullable();
            $table->text('cc_bulannfa')->nullable();
            $table->text('cd_tahunnfa')->nullable();
            $table->text('ce_tarikhad')->nullable();
            $table->text('cf_bulanad')->nullable();
            $table->text('cg_tahunad')->nullable();
            $table->text('ch_tarikhkestutup')->nullable();
            $table->text('ci_bulankestutup')->nullable();
            $table->text('cj_tahunkestutup')->nullable();
            $table->text('ck_statuskes')->nullable();
            $table->text('cl_pergerakanep')->nullable();
            $table->text('cm_statuseksibit')->nullable();
            $table->text('cn_week')->nullable();
            $table->text('co_tpr')->nullable();
            $table->text('cp_bsdalamsiasatan')->nullable();
            $table->text('tkh_jkrk')->nullable();
            $table->text('nilai_rayuan')->nullable();
            $table->text('status_kes2')->nullable();
            $table->text('kategori_kes')->nullable();
            $table->string('kod_negeri')->nullable();
            $table->string('kod_cawangan')->nullable();
            $table->string('status_kes')->nullable();
            $table->string('status_kes_det')->nullable();
            $table->string('kesbrg_id')->nullable();
            $table->date('tkh_kejadian')->nullable();
            $table->date('tkh_serahan')->nullable();
            $table->date('tkh_kompaun_dikeluarkan')->nullable();
            $table->date('tkh_kompaun_diserahkan')->nullable();
            $table->date('tkh_kompaun_dibayar')->nullable();
            $table->date('tkh_daftar_mahkamah')->nullable();
            $table->date('tkh_sebutan')->nullable();
            $table->date('tkh_bicara')->nullable();
            $table->date('tkh_denda')->nullable();
            $table->date('tkh_penjara')->nullable();
            $table->date('tkh_dnaa')->nullable();
            $table->date('tkh_nfa')->nullable();
            $table->date('tkh_ad')->nullable();
            $table->date('tkh_kes_tutup')->nullable();
            $table->string('tmp1')->nullable();
            $table->string('no_kes')->nullable();
            $table->string('akta')->nullable();
            $table->string('asas_tindakan')->nullable();
            $table->string('pengelasan_kes')->nullable();
            $table->string('no_report_polis')->nullable();
            $table->decimal('nilai_award_app_shj')->nullable();
            $table->decimal('nilai_kompaun_ditawarkan')->nullable();
            $table->decimal('nilai_kompaun_dibayar')->nullable();
            $table->string('taraf_kerakyatan')->nullable();
            $table->string('catatan_kerakyatan')->nullable();
            $table->string('no_resit_pembayaran_kompaun')->nullable();
            $table->decimal('nilai_denda')->nullable();
            $table->string('kategori_brg_rampasan')->nullable();
            $table->string('jenis_brg_rampasan')->nullable();
            $table->string('jenis_brg_rampasan2')->nullable();
            $table->string('karya_tempatan_antarabangsa')->nullable();
            $table->string('jenama_brg_rampasan')->nullable();
            $table->decimal('unit')->nullable();
            $table->decimal('tong')->nullable();
            $table->decimal('tangki')->nullable();
            $table->decimal('liter')->nullable();
            $table->decimal('kg')->nullable();
            $table->decimal('nilai_rampasan')->nullable();
            $table->decimal('nilai_kenderaan')->nullable();
            $table->unsignedInteger('created_by')->nullable();
            $table->timestamps();
            $table->unsignedInteger('updated_by')->nullable();
            $table->unsignedInteger('deleted_by')->nullable();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('enquiry_paper_case_temps');
    }
}
